dist: xenial
language: php
php:
  # the latest and greatest, has some issues that are excluded below in matrix.allow_failures
  - 7.3
  - 7.2
  - 7.1
  # the 7.0 build demonstrates that everything is basically ok for 7.0, users might want to wait for 7.1 to run it
  - 7.0
  # folks who prefer running on 5.x should be using 5.6 in most cases, 5.4 is no in the matrix since noone should use it
  - 5.6
services:
  - postgresql

env:
  global:
    - ENVIRONMENT=testing
    - LIBRETIME_LOG_DIR=/tmp/log/libretime

addons:
  apt:
    packages:
      - silan
      - libgirepository1.0-dev
      - gir1.2-gstreamer-1.0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - libcairo2-dev
      - liquidsoap
      - liquidsoap-plugin-mad
      - liquidsoap-plugin-taglib
      - liquidsoap-plugin-flac
      - liquidsoap-plugin-ogg
      - liquidsoap-plugin-lame
      - liquidsoap-plugin-faad
      - liquidsoap-plugin-vorbis
      - liquidsoap-plugin-opus
      - python3
      - python3-nose
      - python3-gst-1.0
      - python3-magic
      - dos2unix
install:
  - >
    if [[ "$PYTHON" == false ]]; then
      composer install
    fi
  - >
    if [[ "$PYTHON" == true ]]; then
      pyenv local 3.7
      pip3 install -U pip wheel
      pip3 install --user mkdocs rgain3
      pushd python_apps/airtime_analyzer
      python3 setup.py install --dry-run --no-init-script
      popd
    fi
before_script:
  - psql -c 'CREATE DATABASE libretime;' -U postgres
  - psql -c "CREATE USER libretime WITH PASSWORD 'libretime';" -U postgres
  - psql -c 'GRANT CONNECT ON DATABASE libretime TO libretime;' -U postgres
  - psql -c 'ALTER USER libretime CREATEDB;' -U postgres
  - mkdir -p /tmp/log/libretime
script: ./travis/test.sh
