version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: libretime
      POSTGRES_PASSWORD: libretime
    healthcheck:
      test: pg_isready -U libretime

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_VHOST: /libretime
      RABBITMQ_DEFAULT_USER: libretime
      RABBITMQ_DEFAULT_PASS: libretime
    healthcheck:
      test: rabbitmq-diagnostics -q ping

volumes:
  postgres_data: {}
