general:
  public_url: http://localhost:8080
  api_key: some_secret_api_key
  secret_key: some_secret_key

database:
  host: postgres

rabbitmq:
  host: rabbitmq

email:
  host: mailpit
  port: 1025

playout:
  liquidsoap_host: liquidsoap

liquidsoap:
  server_listen_address: 0.0.0.0

  harbor_ssl_certificate: /certs/fake.crt
  harbor_ssl_private_key: /certs/fake.key

stream:
  inputs:
    main:
      public_url: https://localhost:8001/main
      mount: main
      port: 8001
      secure: true

  outputs:
    .default_icecast_output: &default_icecast_output
      host: icecast
      port: 8000
      source_password: hackme
      admin_password: hackme
      name: LibreTime!
      description: LibreTime Radio!
      website: https://libretime.org
      genre: various

    icecast:
      - <<: *default_icecast_output
        enabled: true
        mount: main.ogg
        public_url: https://localhost:8443/main.ogg
        audio:
          format: ogg
          bitrate: 256

      - <<: *default_icecast_output
        enabled: true
        mount: main.opus
        public_url: https://localhost:8443/main.opus
        audio:
          format: opus
          bitrate: 256

      - <<: *default_icecast_output
        enabled: true
        mount: main.mp3
        public_url: https://localhost:8443/main.mp3
        audio:
          format: mp3
          bitrate: 256

    hls:
      - # Whether the output is enabled.
        # > default is false
        enabled: false
        # > must be one of ('mpegts', 'mp3', 'adts', 'mp4')
        # > this field is REQUIRED
        format: mpegts
        # > segment_duration  (default:2.0)
        segment_duration: 2.0
        # > segments count  (default:5)
        segment_count: 5
        # > segments_overhead (default:5)
        segments_overhead: 5
        # Output public url, If not defined, the value will be generated from
        # the [general.public_url] hostname, the output port and mount.
        public_url:
        # hls mount point
        # > this field is REQUIRED
        mount: hls/main
        streams:
          - # > prefix of generated fragment
            # > this field is REQUIRED
            fragment_prefix: mp3_low
            # > codec must be one of ( 'libmp3lame', 'flac', 'aac', 'libopus', 'libvorbis')
            # > this field is REQUIRED
            codec: libmp3lame
            # > bitrate of the stream
            # > this field is REQUIRED
            bitrate: 32k
            # > sampling rate (default: 44100Hz)
            sample_rate: 44100
          - fragment_prefix: mp3_med
            codec: libmp3lame
            bitrate: 128k
          - fragment_prefix: mp3_hifi
            codec: libmp3lame
            bitrate: 256k
        # Whether the stream should be used for mobile devices.
        # > default is false
        mobile: false

    system:
      - enabled: false
        kind: pulseaudio
