---
blank_issues_enabled: false
contact_links:
  - name: LibreTime Forum
    url: https://discourse.libretime.org/
    about: Please find existing questions and discussions here.

  - name: LibreTime Chat (#libretime:matrix.org)
    url: https://matrix.to/#/#libretime:matrix.org
    about: Discuss with the LibreTime community.
