name: Analyzer

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/analyzer.yml
      - analyzer/**
      - shared/**

  pull_request:
    branches: [main]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/analyzer.yml
      - analyzer/**
      - shared/**

jobs:
  python:
    uses: ./.github/workflows/_python.yml
    with:
      context: analyzer
