name: API

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/**
      - api/**
      - shared/**

  pull_request:
    branches: [main]
    paths:
      - .github/workflows/**
      - api/**
      - shared/**

jobs:
  python:
    uses: ./.github/workflows/_python.yml
    with:
      context: api
      test: false
      test-with-database: true
