name: Playout

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/playout.yml
      - playout/**
      - api-client/**
      - shared/**
      - tools/python*

  pull_request:
    branches: [main]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/playout.yml
      - playout/**
      - api-client/**
      - shared/**
      - tools/python*

  schedule:
    - cron: 0 1 * * 1

jobs:
  python:
    uses: ./.github/workflows/_python.yml
    with:
      context: playout
