name: Playout

on:
  push:
    branches: [main, 3.0.x]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/playout.yml
      - playout/**
      - api-client/**
      - shared/**

  pull_request:
    branches: [main, 3.0.x]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/playout.yml
      - playout/**
      - api-client/**
      - shared/**

jobs:
  python:
    uses: ./.github/workflows/_python.yml
    with:
      context: playout
