name: Shared

on:
  push:
    branches: [main, 3.0.x]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/shared.yml
      - shared/**

  pull_request:
    branches: [main, 3.0.x]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/shared.yml
      - shared/**

jobs:
  python:
    uses: ./.github/workflows/_python.yml
    with:
      context: shared
