name: Webapp

on:
  workflow_dispatch:
  push:
    branches: [main, stable]
    paths:
      - .github/workflows/webapp.yml
      - webapp/**

  pull_request:
    branches: [main, stable]
    paths:
      - .github/workflows/webapp.yml
      - webapp/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - node-version: "18"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: yarn install --frozen-lockfile
        working-directory: webapp
      - name: Lint
        run: yarn lint
        working-directory: webapp
  
  prettier:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - node-version: "18.12.x"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: yarn install --frozen-lockfile
        working-directory: webapp
      - name: Lint
        run: yarn prettier-check
        working-directory: webapp

  test-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - node-version: "18.12.x"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: yarn install --frozen-lockfile
        working-directory: webapp
      - name: Lint
        run: yarn build
        working-directory: webapp