name: Worker

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/worker.yml
      - worker/**

  pull_request:
    branches: [main]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/worker.yml
      - worker/**

jobs:
  python:
    uses: ./.github/workflows/_python.yml
    with:
      context: worker
