name: Worker

on:
  push:
    branches: [main, stable]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/worker.yml
      - worker/**

  pull_request:
    branches: [main, stable]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/worker.yml
      - worker/**

  schedule:
    - cron: 0 1 * * 1

jobs:
  python:
    uses: ./.github/workflows/_python.yml
    with:
      context: worker
